import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = { title: 'Create Next', description: 'Generated by create next' };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const a = '1';
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
